# Generated by Django 4.1.1 on 2022-09-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_part', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=120, unique=True)),
                ('client_secret', models.CharField(max_length=120, unique=True)),
                ('authorization_endpoint', models.CharField(max_length=400)),
                ('grant_type', models.CharField(max_length=120)),
                ('response_type', models.CharField(max_length=4)),
                ('scopes', models.CharField(max_length=120, unique=True)),
                ('default_scopes', models.CharField(max_length=120, unique=True)),
                ('redirect_uri', models.CharField(max_length=400)),
                ('default_redirect_uri', models.CharField(max_length=400)),
            ],
        ),
    ]
