# Generated by Django 4.1.1 on 2022-09-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_part', '0002_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='default_redirect_uri',
        ),
        migrations.AlterField(
            model_name='client',
            name='authorization_endpoint',
            field=models.CharField(default='http://127.0.0.1:8000/authorize_client/', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='default_scopes',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='client',
            name='grant_type',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='response_type',
            field=models.CharField(default='code', max_length=4),
        ),
        migrations.AlterField(
            model_name='client',
            name='scopes',
            field=models.CharField(max_length=120),
        ),
    ]
