# Generated by Django 4.1.1 on 2022-09-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_part', '0003_remove_client_default_redirect_uri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='grant_type',
            field=models.CharField(default='authorization_code', max_length=120, null=True),
        ),
    ]
