# Generated by Django 4.1.1 on 2022-09-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_part', '0006_authorizationcode_state_client_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_pkce_required',
            field=models.BooleanField(default=True),
        ),
    ]
