# Generated by Django 4.1.1 on 2022-09-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_part', '0007_client_is_pkce_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizationcode',
            name='code',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
