# Generated by Django 4.1.2 on 2022-10-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_part', '0011_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='keys',
            name='kid',
            field=models.CharField(default=3333, max_length=30),
            preserve_default=False,
        ),
    ]
